### PR TITLE
Remove IRC notification from CI.

### PR DESCRIPTION
**Pull request by athas**
This is the only thing that prevents the CI badge from being green (meaning it can also hide other errors).

### CODE REVIEW

**Comment by phadej** [comment]
Note the comment  on top of the file.

**Comment by athas** [comment]
Oh drat.  I will try again.

**Comment by athas** [comment]
I used a newer version of haskell-ci so the diff looks awful now.

**Comment by phadej** [comment]
> I used a newer version of haskell-ci so the diff looks awful now.

That's fine. Contents of `haskell.yml` are somewhat irrelevant, config is the important part.

**Pull request merged**
