### PR TITLE
Track recent changes in warning flag names.

### PR DESCRIPTION
**Pull request by svenpanne**

### CODE REVIEW

**Comment by ekmett** [comment]
_sigh_ This change is going to suck elsewhere.

**Comment by svenpanne** [comment]
Thanks for merging, can we have a release including that tiny fix? This would improve my Travis CI experience... :wink:

**Comment by ekmett** [comment]
Sure

**Comment by ekmett** [comment]
I need to switch to the new release candidate so that I can build first, but once that is done, I'll push.

**Pull request merged**
